volumes:
  pg_data:
  static:

services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: always

  web:
    container_name: imei_checker
    build: ./
    env_file: .env
    volumes:
      - static:/static
      - ./logs:/app/logs
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    restart: always

  gateway:
    container_name: imei_nginx
    build: ./nginx/
    env_file: .env
    ports:
      - 8001:80
    volumes:
      - static:/static
    depends_on:
      - db
      - web
    restart: always
